#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  amixer -q sset Master 5%+
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  amixer -q sset Master toggle
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  amixer -q sset Master 5%-
fi

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
    if [[ $volume -ge 60 ]]; then
        printf "&#xf028; %d%%\n" $volume
    elif [[ $volume -ge 30 ]]; then
        printf "&#xf027; %d%%\n" $volume
    else
        printf "&#xf026; %d%%\n" $volume
    fi

    printf "vol: %d\n" $volume
    printf "\n"    
else
  echo "&#xf6a9; off"
  echo "vol: off"
  echo ""
fi